# -*- coding: utf-8 -*-
"""Using credit model library 1.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xSXlIE0KT_HOnscUmbp5JsHvsLrFR9jS
"""

!pip install git+https://github.com/rajap20/MLOpsProject.git

"""## Checking Library Version Number"""

import creditpredict

creditpredict.__version__

"""## Invoking the library"""

from creditpredict import CreditPredictor, CreditPredictionModel

CreditPredictor?

credit_predictor = CreditPredictor()

"""### Getting help for the predict function"""

credit_predictor.predict?

"""### Predicting the price of an car"""

credit_predictor.predict(area_code  =  '3075.0',
              asset_cost  =  87000.0,
              state  =  "AP",
              loan_amt  =  71000.0,
              resid_type  =  "O",
              emi  =  0.124252,
              net_irr  =  1.321153,
              net_salary  =  0.158169,
              proc_fee  =  0.093758,
              roi  =  0.793282,
              age  =  0.306122,
              tenure  =  0.470588)
